### PR TITLE
A: https://descomplica.com.br/blog/quimica/exercicios-quimica-organica/

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by eduaddad** [comment]
@Khrin 

Could you upgrade please?

**Comment by Khrin** [comment]
I don't have write access here.

**Comment by smed79** [comment]
@monzta @diaux

**Comment by jabonsolo** [comment]
Again sorry for the very very late response, we are trying to reactive the maintenance of the list. This banner seems more like self-promo so I believe this should not be added.

**Pull request closed without merging**
